### ISSUE TITLE
`rescue in parse_string': Caught Encoding::CompatibilityError at ...

### ISSUE THREAD

**Issue by mayoralito** [semmypurewal/node-dev-bootstrap#13]
Hey everyone.

I get an error briefly described in title. see Below:

```
git clone git@github.com:semmypurewal/node-dev-bootstrap.git
cd node-dev-bootstrap/
vagrant up

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'precise32' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
/Users/mayoralito/.vagrant.d/gems/gems/json-1.8.1/lib/json/pure/parser.rb:242:in `rescue in parse_string': Caught Encoding::CompatibilityError at '[{"content-type":"ap': incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string) (JSON::ParserError)
    from /Users/mayoralito/.vagrant.d/gems/gems/json-1.8.1/lib/json/pure/parser.rb:213:in `parse_string'

```

Complete process http://pastebin.com/SKcWaeYt

Hope anyone can help.
Regards.

**Comment by mayoralito** [comment]
It's been more than a year without any update from my side and it's been working good so far. Unless somebody else wants to add something else, I think we can close this thread.
